name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # НАВОДИМ ПОРЯДОК С РЕГИСТРОМ БУКВ:
      # Этот шаг берет имя вашего репозитория, делает его маленькими буквами 
      # и записывает в переменную "repository"
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Используем переменную ${{ env.GITHUB_REPOSITORY_SLUG_CS }} 
          # Она гарантированно будет состоять только из маленьких букв
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_SLUG_CS }}:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
